language: c
compiler: gcc
sudo: required
dist: trusty

env:
  jobs:
    - DISTRO="Fedora 31"
    - DISTRO="Fedora 32"
    - DISTRO="Fedora 33"
    - DISTRO="Fedora rawhide"
    - DISTRO="CentOS 7"
    - DISTRO="CentOS 8"

arch:
  - amd64
  - ppc64le
  - arm64
  - s390x

os: linux

script: ./.travis/travis.sh

jobs:
  fast_finish: true
  exclude:
    - arch: s390x
      env: DISTRO="CentOS 7"
    - arch: s390x
      env: DISTRO="CentOS 8"
  include:
    - stage: "Static Analysis"
      name: "Coverity Scan"
      script: ./.travis/travis-coverity.sh
      arch: amd64
      env:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
        - secure: "Aca0+L1CYqdRTi5T9aeDM7Es6E9eIbRyFhUlBjqEpSJVkk5mgXWAANuiiqWSr69k7aI5WDiuAZGyGqg/9nkVOaJfiJ1a+AmtN/UEvT0IXmn4nCZupiR4aGHUGYwwY6UD9nvHL92BFx21oTyEnd+XlcHjP0jcwmma0P7fc4xK5bIXPHF/nLs2Xm3aw9iuD6WY7gZ+NZPr/BAcAAc3RQtBWC8hQaTn3V1NDTx7Vj5SolQCDii1lwNSw7L8ozaaKFrkwaJqtClkVqQwujYnP4gnFIURRPiM8sy2mKWlQMj5aOyZP7oEuSYMV5Qe9QS6MYqNc8jSHyswM58s1dVnHtaeL/k5fwwyXKA8eEpmpsy1iNzyru6A36mH94QzTVxqjJO5BeQCo18CveqsxP2Y/HE1JeO/79IRpKBWzB99PDzu5QfQvxLRYzn67QWnzYDGJFUPAkvAiEDFyUglGVWv0Ww67zk+s+UFV62rp8EX9xZxYHab9bWufrqj3Lv8qWMYzP7Fy8yJ/BhmHxxXqDtJWgsq1O3IIiaBjq1ZHGldZe63J6C+F1H5Xa1WyoLqv3CRbfkDOlQh4XGA9FM9tfLAfuVwyfMTc0qPuetGsZuirDIiiHaEb6KXU8YSHVgnjhdJIXx7jcn1DqZ1gHv0nMGZyqF2yjDJaTHMb0lwUedzwOXCXAw="
